name: "Jellyfin-newsletter docker dev image deployment"
permissions:
  contents: read
  packages: write
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-dev.[0-9]+'



jobs:
    security_test:
        uses: ./.github/workflows/security_test.yml 
    build_and_publish :
      needs: [security_test]
      name: Build and publish dev image
      runs-on: ubuntu-latest
      env:
        DOCKER_IMAGE_NAME: "jellyfin-newsletter"
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        
        - name: Extract Git commit
          id: vars
          run: echo "GIT_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

        - name: Set up Qemu 
          uses: docker/setup-qemu-action@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to GHCR 
          users: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and push Docker images
          uses: docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: |
              ghcr.io/${{ secrets.USERNAME }}/jellyfin-newsletter:dev
              ghcr.io/${{ secrets.USERNAME }}/jellyfin-newsletter:${{ github.ref_name }}
            labels: |
              org.opencontainers.image.revision=${{ env.GIT_COMMIT }}
              org.opencontainers.image.created=${{ steps.meta.outputs.created }}
              org.opencontainers.image.version=${{ github.ref_name }}
            cache-from: type=gha
            cache-to: type=gha,mode=max
            platforms: linux/amd64,linux/arm64,linux/arm/v7